'use strict';

/**
 * @ngdoc overview
 * @name testApp
 * @description # testApp
 * 
 * Main module of the application.
 */
// 应用主模块
var app = angular.module('adminApp', [ 'admin', "templateAdminModule", "rankAdminModule", "restaurantAdminModule", "userAdminModule", "feedbackAdminModule", 
	"firstPageAdminModule", "messageAdminModule", "statisticsAdminModule", "categoryAdminModule", "moduleAdminModule", "lessonAdminModule", "videoSetAdminModule", 
	"praiseAdminModule", "lessonStatAdminModule"])
	.filter("templateTypes", function(){
		return function (data) {
			if(data == "CUSTOM"){
				return 'template.type.custom';
			}else if(data == "TEAM_APPLY"){
				return 'template.type.team.apply';
			}else if(data == "TEAM_INVITE"){
				return 'template.type.team.invite';
			}else if(data == "NEW_LESSON_ASSIGN"){
				return 'template.type.new.lesson.assign';
			}else if(data == "TRAINEE_REGIST_SUCCESS"){
				return 'template.type.trainee.regist.success';
			}else if(data == "CHEF_REGIST_SUCCESS"){
				return 'template.type.chef.regist.success';
			}else{
				return 'common.unknown';
			}
		}
	});

app.config(['$translateProvider', function($translateProvider) {

	$translateProvider.translations('zh', {
		'common.unknown':'未知',
		'common.search.not.result' : '没有查询到任何数据,请修改查询条件并重试',
		'common.password':'修改密码',
		'common.logout':'退出',
		'common.save' : '保存',
		'common.query': '查询',
		'common.clean': '清空',
		'common.operation' : '操作',
		'common.update' : '修改',
		'common.delete' : '删除',
		'common.view': '查看',
		'common.enable':'启用',
		'common.disable':'禁用',
		'common.index': '序号',
		'common.reply':'回复',
		
		'common.page.previous' : '前页',
		'common.page.next' : '后页',
		'common.page.first' : '首页',
		'common.page.last' : '尾页',
		
		'common.date.clear' : '清空',
		'common.date.close' : '关闭',
		'common.date.current' : '今天',
		
		'common.startTime':'开始时间',
		'common.endTime':'结束时间',
		
		'firstPage.title':'欢迎使用Toque管理后台',
		'firstPage.title.today':'Toque应用今日数据概况',
		'firstPage.title.week':'Toque应用近7日数据概况',
		'firstPage.title.total':'Toque应用累计数据概况',
		'firstPage.loginTime':'当前账号最后一次登录时间为',
		'firstPage.user.all':'总用户累计',
		'firstPage.user.pay.total.all':'付费用户累计',
		'firstPage.user.play.avg':'用户播放视频的平均次数',
		'firstPage.user.play.total':'课程播放总次数',
		'firstPage.user.new.all':'新用户',
		'firstPage.user.active.all':'活跃用户',
		'firstPage.user.pay.all':'新付费用户',
		'firstPage.user.chef':'主厨用户',
		'firstPage.user.trainee':'学员用户',
		'firstPage.level.vip2':'小团队',
		'firstPage.level.vip3':'中团队',
		'firstPage.level.vip4':'大团队',
		'firstPage.video.play.all':'视频播放次数',
		'firstPage.video.play.total':'视频播放总次数',
		'firstPage.week.play.avg':'课程播放平均时长',
		'firstPage.week.assign.avg':'指派课程平均次数',
		'firstPage.week.kinchen.all':'Kinchen页面访问次数',
		
		
		'template.manage' : '通知模板管理',
		'template.create' : '创建通知模板',
		'template.form.title': '模板信息',
		'template.number': '模板编号',
		'template.type': '模板类型',
		'template.type.custom': '自定义',
		'template.type.team.apply': '团队申请',
		'template.type.team.invite': '团队邀请',
		'template.type.new.lesson.assign': '新课程指派',
		'template.type.trainee.regist.success': '学员注册成功',
		'template.type.chef.regist.success': '主厨注册成功',
		
		'template.content.chinese' : '模板內容(中文)',
		'template.content.chinese.error' : '模板內容(中文)不能为空',
		'template.content.english' : '模板內容(英文)',
		'template.content.english.error' : '模板內容(英文)不能为空',
		'template.content.sms.chinese':'短信模板(中文)',
		'template.content.sms.english':'短信模板(英文)',
		'template.content.email.chinese':'邮件模板(中文)',
		'template.content.email.english':'邮件模板(英文)',
		'template.email.title.chinese':'邮件标题(中文)',
		'template.email.title.english':'邮件标题(英文)',
		
		'template.scope' : '通知对象',
		'template.scope.all':'全部用户',
		'template.scope.all.chef':'全部主厨',
		'template.scope.all.trainee':'全部学员',
		'template.scope.single':'单个用户',
		'template.immediately' : '发送方式',
		'template.immediatelys.true':'立即发送',
		'template.immediatelys.false':'定时发送',
		'template.planSendTime' : '计划发送时间',
		'template.link' : '指定链接',
		'template.link.placeholder' : '为空则不跳转',
		'template.sendSmsAndEmail' : '同步发送短信/邮件',
		
		
		'rank.manage' : '身份字典管理',
		'rank.number':'身份编号',
		'rank.name':'身份名称',
		'rank.memo':'备注',
		'rank.createdTime':'创建时间',
		'rank.1.number':'001',
		'rank.1.name':'主厨',
		'rank.1.memo':'升级餐厅特权&管理餐厅团队&指派培训课程',
		'rank.1.createdTime':'2018-01-01 10:00:00',
		'rank.2.number':'002',
		'rank.2.name':'学员',
		'rank.2.memo':'申请加入餐厅团队&学习培训课程',
		'rank.2.createdTime':'2018-01-01 10:00:00',
		
		'restaurant.manage' : '餐厅字典管理',
		'restaurant.create' : '创建餐厅',
		'restaurant.name' : '餐厅名称',
		'restaurant.condition.pay' : '全部餐厅',
		'restaurant.condition.pay.true':'已付费餐厅',
		'restaurant.condition.pay.false':'未付费餐厅',
		'restaurant.inviteCode':'邀请码',
		'restaurant.name':'餐厅名称',
		'restaurant.type':'餐厅类型',
		'restaurant.dishType':'餐厅菜式',
		'restaurant.enable':'有效标识',
		'restaurant.enable.true':'有效',
		'restaurant.enable.false':'无效',
		'restaurant.level':'特权等级',
		'restaurant.level.vip0':'体验版',
		'restaurant.level.vip1':'付费版',
		'restaurant.level.vip2':'专业版（小团队）',
		'restaurant.level.vip3':'专业版（中团队）',
		'restaurant.level.vip4':'专业版（大团队）',
		'restaurant.teamLimit':'团队上限',
		'restaurant.prerogativeEndTime':'特权到期时间',
		'restaurant.pay':'是否付费',
		'restaurant.pay.true':'是',
		'restaurant.pay.false':'否',
		'restaurant.payLevel':'付费等级',
		'restaurant.creator':'创建者',
		'restaurant.createdTime':'创建时间',
		'restaurant.users':'当前学员人数',
		
		'user.manage':'用户信息管理',
		'user.country':'国家',
		'user.userType.all':'全部身份',
		'user.userType.chef':'主厨',
		'user.userType.trainee':'学员',
		'user.phone':'手机号码',
		'user.email':'邮箱',
		'user.userType':'身份',
		'user.languageType':'语种',
		'user.languageType.chinese':'中文',
		'user.languageType.english':'英语',
		'user.realname':'姓名',
		'user.position':'职位',
		'user.lastLoginTime':'最后登录时间',
		'user.registTime':'注册时间',
		'user.enable':'账户状态',
		'user.enable.true':'有效',
		'user.enable.false':'无效',
		'user.new':'新用户',
		'user.old':'老用户',
		'user.new.percent':'新用户占比',
		'user.old.percent':'老用户占比',
		'user.start':'启动用户',
		'user.assign':'必修课程数',
		
		
		'feedback.manage':'使用反馈管理',
		'feedback.username':'反馈用户',
		'feedback.createdTime':'反馈时间',
		'feedback.content':'反馈内容',
		'feedback.reply':'回复内容',
		'feedback.reply.error':'回复内容不能为空',
		'feedback.status':'处理状态',
		'feedback.status.waiting':'未处理',
		'feedback.status.replyed':'已回复',
		'feedback.form.title':'反馈信息',
		
		'message.manage':'发送历史',
		'message.user':'通知对象',
		'message.content':'通知内容',
		'message.createdTime':'发送时间',
		'meesage.type.all':'全部类型',
		
		'stat.active.unit.day':'日活跃用户',
		'stat.active.unit.week':'周活跃用户',
		'stat.active.unit.month':'月活跃用户',
		
		'statistics.user.new':'新用户统计',
		'statistics.user.active':'活跃用户统计',
		'statistics.user.pay':'付费用户统计',
		
		'lessonStat.scope.yesterday':'昨日',
		'lessonStat.scope.week':'近7日',
		'lessonStat.scope.total':'累计',
		'lessonStat.playPv':'播放次数PV',
		'lessonStat.playUv':'播放次数UV',
		'lessonStat.avgTime':'平均播放时长',
		'lessonStat.finished':'播放完毕次数',
		'lessonStat.assigned':'被指派次数',
		'lessonStat.praised':'点赞数',
		'lessonStat.criticism':'点踩数',
		'lessonStat.manage':'餐厅事件监控',
		
		'category.manage':'门类信息管理',
		'category.create':'新建门类',
		'category.title':'中文名称',
		'category.titleE':'英文名称',
		'category.moduleCount':'模块数量',
		'category.createdTime':'创建时间',
		'category.form.title':'门类信息',
		
		'module.manage':'课程模块管理',
		'module.create':'新建课程模块',
		'module.title':'中文名称',
		'module.titleE':'英文名称',
		'module.type':'模块属性',
		'module.type.free':'免费',
		'module.type.pay':'付费',
		'module.type.hot':'预热',
		'module.lessonCount':'课程数量',
		'module.createdTime':'创建时间',
		'module.form.title':'课程模块信息',
		'module.tag':'中文标签',
		'module.tagE':'英文标签',
		'module.cover':'中文封面',
		'module.coverE':'英文封面',
		'module.desc':'中文描述',
		'module.descE':'英文描述',
		'module.categoryId':'所属门类',
		
		'lesson.title':'课程标题(中文)',
		'lesson.titleE':'课程标题(英文)',
		'lesson.second':'时长',
		'lesson.difficulty':'难度',
		'lesson.difficulty.easy':'简单',
		'lesson.difficulty.normal':'普通',
		'lesson.difficulty.hard':'困难',
		'lesson.moduleId':'所属模块',
		'lesson.tag':'标签(中文)',
		'lesson.tagE':'标签(英文)',
		'lesson.tag.placeholder':'以英文逗号隔开',
		'lesson.tagE.placeholder':'以英文逗号隔开',
		'lesson.cover':'封面(中文)',
		'lesson.coverE':'封面(英文)',
		'lesson.graph':'信息图(中文)',
		'lesson.graphE':'信息图(英文)',
		'lesson.ingredients':'食材(中文)',
		'lesson.ingredientsE':'食材(英文)',
		'lesson.ingredients.placeholder':'以英文逗号隔开',
		'lesson.ingredientsE.placeholder':'以英文逗号隔开',
		'lesson.steps':'图文步骤(中文)',
		'lesson.stepsE':'图文步骤(英文)',
		'lesson.manage':'课程信息管理',
		'lesson.create':'新建课程信息',
		'lesson.form.title':'课程信息',
		'lesson.createdTime':'创建时间',
		'lesson.steps.content':'文字说明',
		'lesson.steps.image':'图片地址',
		
		'videoSet.manage':'视频集管理',
		'videoSet.create.video':'创建视频集(启动:视频)',
		'videoSet.create.image':'创建视频集(启动:图片)',
		'videoSet.name':'视频集名称',
		'videoSet.form.title':'视频集信息',
		'videoSet.interaction':'交互事件',
		'videoSet.rightCount':'请选择对错事件数',
		'videoSet.multiCount':'请选择多选项事件数',
		'videoSet.interaction.create':'生成模板',
		'videoSet.videoGroup.main':'主视频组',
		'videoSet.video.main':'主视频',
		'videoSet.video.url':'视频地址',
		'videoSet.interaction.select':'请选择交互结果',
		'videoSet.videoGroup':'视频组',
		'videoSet.interaction.image':'交互图片地址',
		'videoSet.video.sub':'子视频',
		'videoSet.videoGroup.right':'为正确选项',
		'videoSet.video.add':'添加选项',
		'videoSet.video.reset':'重置',
		'videoSet.startWithImage':'启动方式',
		'videoSet.lesson':'关联课程',
		'videoSet.createdTime':'创建时间',
		'videoSet.modifyTime':'最后修改时间',
		'videoSet.startWithImage.true':'图片',
		'videoSet.startWithImage.false':'视频',
		'videoSet.interaction.select.no':'无交互',
		
		'praise.manage':'课程质量统计',
		'praise.lessonName':'课程标题',
		'praise.username':'用户',
		'praise.content':'统计结果',
		'praise.createdTime':'统计时间',
		
		'password.old':'旧密码',
		'password.new':'新密码',
		'password.confirm':'确认新密码',
		'password.confirm.error':'两次输入的密码不相同',
	});
	
	$translateProvider.translations('en', {
		'common.unknown':'Unknown',
		'common.search.not.result' : 'No result , please modify search critera and retry',
		'common.password':'Change Password',
		'common.logout':'Logout',
		'common.save' : 'Save',
		'common.query': 'Search',
		'common.clean': 'Clean out',
		'common.operation' : ' Operate',
		'common.update' : 'Modify',
		'common.delete' : 'Delete',
		'common.view': 'View',
		'common.enable':'Enable',
		'common.disable':'Disable',
		'common.index': 'Serial number',
		'common.reply':'Reply',

		'common.page.previous' : 'Previous page',
		'common.page.next' : 'Next page',
		'common.page.first' : 'Home page',
		'common.page.last' : 'Last page',

		'common.date.clear' : 'Clean',
		'common.date.close' : 'Close',
		'common.date.current' : 'Today',

		'common.startTime':'Start time',
		'common.endTime':'End time',

		'firstPage.title':"Welcome to use the toque's management system",
		'firstPage.loginTime':'The last login',
		'firstPage.user.all':'Cumulative users',
		'firstPage.user.new.all':'New users',
		'firstPage.user.active.all':'Active users',
		'firstPage.user.pay.all':'New paid user',
		'firstPage.user.chef':'Chef',
		'firstPage.user.trainee':'Apprentice',
		
		
		
		'firstPage.title':"Welcome to use the toque's management system",
		'firstPage.title.today':'Today info',
		'firstPage.title.week':'Week info',
		'firstPage.title.total':'Total info',
		'firstPage.loginTime':'The last login',
		'firstPage.user.all':'Cumulative users',
		'firstPage.user.pay.total.all':'Paid user total',
		'firstPage.user.play.avg':'Video play avg',
		'firstPage.user.play.total':'Video play count',
		'firstPage.user.new.all':'New users',
		'firstPage.user.active.all':'Active users',
		'firstPage.user.pay.all':'New paid user',
		'firstPage.user.chef':'Chef',
		'firstPage.user.trainee':'Apprentice',
		'firstPage.level.vip2':'small team',
		'firstPage.level.vip3':'middle team',
		'firstPage.level.vip4':'large team',
		'firstPage.video.play.all':'Video paly',
		'firstPage.video.play.total':'Video paly count',
		'firstPage.week.play.avg':'Video play avg time',
		'firstPage.week.assign.avg':'Video assign avg time',
		'firstPage.week.kinchen.all':'Kinchen页面访问次数',

		'template.manage' : 'Template for notification',
		'template.create' : 'Add template for notification ',
		'template.form.title': 'Template information',
		'template.number': 'Template number',
		'template.type': 'Template type',
		'template.type.custom': 'Custom',
		'template.type.team.apply': 'Team apply',
		'template.type.team.invite': 'Team invite',
		'template.type.new.lesson.assign': '新课程指派',
		'template.type.trainee.regist.success': 'Registration complete（Apprentice）',
		'template.type.chef.regist.success': 'Registration complete（Chef）',
		'template.content.chinese' : 'Template content（CN）',
		'template.content.chinese.error' : "Template content（CN） can't be empty",
		'template.content.english' : 'Template content（EN）',
		'template.content.english.error' : "Template content（EN） can't be empty",
		'template.scope' : 'Notification object',
		'template.scope.all':'All users',
		'template.scope.all.chef':'All chefs',
		'template.scope.all.trainee':'All apprentices',
		'template.scope.single':'Single user',
		'template.immediately' : 'Sending mode',
		'template.immediatelys.true':'Send now',
		'template.immediatelys.false':'Timing sending',
		'template.planSendTime' : 'Sending plan',
		'template.link' : 'Link',
		'template.link.placeholder' : 'Not go to URL if empty',
		'template.sendSmsAndEmail' : 'Send message/email at the same time',

		'rank.manage' : "Identity's dictionary",
		'rank.number':"Identity's number",
		'rank.name':"Identity's name",
		'rank.memo':'Notes',
		'rank.createdTime':'Create time',
		'rank.1.number':'001',
		'rank.1.name':'Chef',
		'rank.1.memo':'Upgrade restaurant privileges & Manage team',
		'rank.1.createdTime':'2018-01-01 10:00:00',
		'rank.2.number':'002',
		'rank.2.name':'Apprentice',
		'rank.2.memo':'Join the team & Learn the courses',
		'rank.2.createdTime':'2018-01-01 10:00:00',

		'restaurant.manage' : "Restaurant's dictionary",
		'restaurant.create' : 'Add restaurant',
		'restaurant.name' : "Restaurant's name",
		'restaurant.condition.pay' : 'All',
		'restaurant.condition.pay.true':'Only paid restaurants',
		'restaurant.condition.pay.false':'Not paid restaurants',
		'restaurant.inviteCode':'Invitation code',
		'restaurant.name':"Restaurant's name",
		'restaurant.type':"Restaurant's type",
		'restaurant.dishType':"Restaurant's dishes",
		'restaurant.enable':'Valid/Invalid',
		'restaurant.enable.true':'Valid',
		'restaurant.enable.false':'Invalid',
		'restaurant.level':'Level',
		'restaurant.level.vip0':'Free Trial',
		'restaurant.level.vip1':'Upgrade trial',
		'restaurant.level.vip2':'Small team',
		'restaurant.level.vip3':'Medium team',
		'restaurant.level.vip4':'Large team',
		'restaurant.teamLimit':'Upper limit of Apprentice',
		'restaurant.prerogativeEndTime':'Due time',
		'restaurant.pay':'Paid/Unpaid',
		'restaurant.pay.true':'Paid',
		'restaurant.pay.false':'Unpaid',
		'restaurant.payLevel':'Payment plan',
		'restaurant.creator':'Creator',
		'restaurant.createdTime':'Create time',
		'restaurant.users':'User Count',
		
		'user.manage':'User information management',
		'user.country':'Country',
		'user.userType.all':'All identity',
		'user.userType.chef':'Chef',
		'user.userType.trainee':'Apprentice',
		'user.phone':'Phone number',
		'user.email':'Email',
		'user.userType':'identity',
		'user.languageType':'Languages',
		'user.languageType.chinese':'Chinese',
		'user.languageType.english':'English',
		'user.realname':'Name',
		'user.position':'Position',
		'user.lastLoginTime':'Last login time',
		'user.registTime':'Registration time',
		'user.enable':'Valid/Invalid',
		'user.enable.true':'Valid',
		'user.enable.false':'Invalid',
		'user.new':'New users',
		'user.old':'Old users',
		'user.new.percent':'New users percentage',
		'user.old.percent':'Old users percentage',
		'user.start':'Users started',
		'user.assign':'Lessons',

		'feedback.manage':'Feedback management',
		'feedback.username':'User account',
		'feedback.createdTime':'Feedback time',
		'feedback.content':'Feedback content',
		'feedback.reply':'Reply content',
		'feedback.reply.error':"Reply content can't be empty",
		'feedback.status':'Processing results',
		'feedback.status.waiting':'Unprocessed',
		'feedback.status.replyed':'processed',
		'feedback.form.title':'Feedback',

		'message.manage':'Feedback',
		'message.user':'Notification object',
		'message.content':'Notification object',
		'message.createdTime':'Send time',
		'meesage.type.all':'ALL',
		
		'stat.active.unit.day':'Day',
		'stat.active.unit.week':'Week',
		'stat.active.unit.month':'Month',
		
		'statistics.user.new':'New user statistics',
		'statistics.user.active':'Active user statistics',
		'statistics.user.pay':'Paid user statistics',
		
		'lessonStat.scope.yesterday':'Yesterday',
		'lessonStat.scope.week':'Last Week',
		'lessonStat.scope.total':'Total',
		'lessonStat.playPv':'PV',
		'lessonStat.playUv':'UV',
		'lessonStat.avgTime':'Avg Time',
		'lessonStat.finished':'Finished',
		'lessonStat.assigned':'Assigned',
		'lessonStat.praised':'Praised',
		'lessonStat.criticism':'riticism',
		'lessonStat.manage':'Lesson Statistics',

		'category.manage':'Classification management',
		'category.create':'Add classification',
		'category.title':'Title（CN）',
		'category.titleE':'Title（CN）',
		'category.moduleCount':'Title（CN）',
		'category.createdTime':'Title（CN）',
		'category.form.title':'Details',

		'module.manage':'Module management',
		'module.create':'Add module',
		'module.title':'Title（CN）',
		'module.titleE':'Title（CN）',
		'module.type':'Property',
		'module.type.free':'Free',
		'module.type.pay':'Paid',
		'module.type.hot':'Coming',
		'module.lessonCount':'Quantity of course',
		'module.createdTime':'Create time',
		'module.form.title':'Details',
		'module.tag':'Tag（CN）',
		'module.tagE':'Tag（EN）',
		'module.cover':'Cover image（CN）',
		'module.coverE':'Cover image（CN）',
		'module.desc':'Description（CN）',
		'module.descE':'Description（EN）',
		'module.categoryId':'Classification',

		'lesson.title':'Title（CN）',
		'lesson.titleE':'Title（EN）',
		'lesson.second':'Duration',
		'lesson.difficulty':'Difficulty',
		'lesson.difficulty.easy':'Easy',
		'lesson.difficulty.normal':'Normal',
		'lesson.difficulty.hard':'Hard',
		'lesson.moduleId':'Module',
		'lesson.tag':'Tag（CN）',
		'lesson.tagE':'Tag（EN）',
		'lesson.tag.placeholder':'Separated by comma',
		'lesson.tagE.placeholder':'Separated by comma',
		'lesson.cover':'Cover image（CN）',
		'lesson.coverE':'Cover image（EN）',
		'lesson.graph':'Summary（CN）',
		'lesson.graphE':'Summary（EN）',
		'lesson.ingredients':'Ingredients（CN）',
		'lesson.ingredientsE':'Ingredients（EN）',
		'lesson.ingredients.placeholder':'Separated by comma',
		'lesson.ingredientsE.placeholder':'Separated by comma',
		'lesson.steps':'Steps（CN）',
		'lesson.stepsE':'Steps（EN）',
		'lesson.manage':'Course management',
		'lesson.create':'Add course',
		'lesson.form.title':'Details',
		'lesson.createdTime':'Create time',
		'lesson.steps.content':'Explanatory text',
		'lesson.steps.image':'Image URL',

		'videoSet.manage':' Video combination management',
		'videoSet.create.video':'Add video（Start with video）',
		'videoSet.create.image':'Add video（Start with image）',
		'videoSet.name':"Video combination's title",
		'videoSet.form.title':"Video combination's detail",
		'videoSet.interaction':'Interaction case',
		'videoSet.rightCount':'Select Number of cases（right/wrong）',
		'videoSet.multiCount':'Select Number of cases（Multiple）',
		'videoSet.interaction.create':'Generate template',
		'videoSet.videoGroup.main':'Main video group',
		'videoSet.video.main':'Main video',
		'videoSet.video.url':'Video URL',
		'videoSet.interaction.select':'Select interactive results',
		'videoSet.videoGroup':'Video group',
		'videoSet.interaction.image':'interactive image URL',
		'videoSet.video.sub':'Subvideo',
		'videoSet.videoGroup.right':'is correct option',
		'videoSet.video.add':'Add video',
		'videoSet.video.reset':'Reset',
		'videoSet.startWithImage':'Startup mode',
		'videoSet.lesson':'Course',
		'videoSet.createdTime':'Create time',
		'videoSet.modifyTime':'The last modify',
		'videoSet.startWithImage.true':'image URL',
		'videoSet.startWithImage.false':'video URL',
		'videoSet.interaction.select.no':'Not Select',

		'praise.manage':'Course quality statistics',
		'praise.lessonName':'Title',
		'praise.username':'User account',
		'praise.content':'Result',
		'praise.createdTime':'Statistical time',
		
		'password.old':'Old Password',
		'password.new':'New Password',
		'password.confirm':'Confirm New Password',
		'password.confirm.error':'New Password and Confirm New Password mismatching',
	});
	
//    var lang;
//    var position = window.location.href.indexOf("?lang=");
//    if(position != -1) {
//    	lang = window.location.href.substr(position + 6, 2);
//    }
//    
//    if(lang == 'zh'){
//    	$translateProvider.preferredLanguage('zh');
//    }else if(lang == 'en'){
//    	$translateProvider.preferredLanguage('en');
//    }else{
//    	$translateProvider.preferredLanguage('zh');
//    }
	
}]);

//var currentLang = navigator.language;   
//if(!currentLang){
//    currentLang = navigator.browserLanguage;
//}
//alert(currentLang);